{"cells":[{"cell_type":"code","execution_count":1,"metadata":{"_cell_guid":"b1076dfc-b9ad-4769-8c92-a6c4dae69d19","_uuid":"8f2839f25d086af736a60e9eeb907d3b93b6e0e5","execution":{"iopub.execute_input":"2023-10-17T11:52:54.587582Z","iopub.status.busy":"2023-10-17T11:52:54.587124Z","iopub.status.idle":"2023-10-17T11:53:02.022942Z","shell.execute_reply":"2023-10-17T11:53:02.021981Z","shell.execute_reply.started":"2023-10-17T11:52:54.587542Z"},"trusted":true},"outputs":[{"name":"stdout","output_type":"stream","text":["Unexpected exception formatting exception. Falling back to standard exception\n"]},{"name":"stderr","output_type":"stream","text":["Traceback (most recent call last):\n","  File \"/home/sidd462/miniconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3526, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"/tmp/ipykernel_9869/3144071719.py\", line 3, in <module>\n","    from matplotlib import pyplot as plt\n","ModuleNotFoundError: No module named 'matplotlib'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/home/sidd462/miniconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 2120, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(\n","          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/home/sidd462/miniconda3/lib/python3.11/site-packages/IPython/core/ultratb.py\", line 1435, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/home/sidd462/miniconda3/lib/python3.11/site-packages/IPython/core/ultratb.py\", line 1326, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/home/sidd462/miniconda3/lib/python3.11/site-packages/IPython/core/ultratb.py\", line 1173, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/home/sidd462/miniconda3/lib/python3.11/site-packages/IPython/core/ultratb.py\", line 1063, in format_exception_as_a_whole\n","    self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []\n","    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/home/sidd462/miniconda3/lib/python3.11/site-packages/IPython/core/ultratb.py\", line 1115, in get_records\n","    style = stack_data.style_with_executing_node(style, self._tb_highlight)\n","            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/home/sidd462/miniconda3/lib/python3.11/site-packages/stack_data/core.py\", line 424, in style_with_executing_node\n","    class NewStyle(style):\n","  File \"/home/sidd462/miniconda3/lib/python3.11/site-packages/pygments/style.py\", line 91, in __new__\n","    ndef[4] = colorformat(styledef[3:])\n","              ^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/home/sidd462/miniconda3/lib/python3.11/site-packages/pygments/style.py\", line 58, in colorformat\n","    assert False, \"wrong color format %r\" % text\n","AssertionError: wrong color format 'ansiyellow'\n"]}],"source":["import os\n","import numpy as np\n","from matplotlib import pyplot as plt\n","%matplotlib inline\n","import keras\n","print(\"keras version: \", keras.__version__)\n","\n","import tensorflow as tf\n","print(\"tensoflow version: \", tf.__version__)"]},{"cell_type":"code","execution_count":2,"metadata":{"execution":{"iopub.execute_input":"2023-10-17T11:53:02.025863Z","iopub.status.busy":"2023-10-17T11:53:02.024729Z","iopub.status.idle":"2023-10-17T11:53:02.030850Z","shell.execute_reply":"2023-10-17T11:53:02.030042Z","shell.execute_reply.started":"2023-10-17T11:53:02.025825Z"},"trusted":true},"outputs":[{"name":"stdout","output_type":"stream","text":["Unexpected exception formatting exception. Falling back to standard exception\n"]},{"name":"stderr","output_type":"stream","text":["Traceback (most recent call last):\n","  File \"/home/sidd462/miniconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3526, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"/tmp/ipykernel_9869/2053465271.py\", line 3, in <module>\n","    tf.random.set_seed(42)\n","    ^^\n","NameError: name 'tf' is not defined\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/home/sidd462/miniconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 2120, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(\n","          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/home/sidd462/miniconda3/lib/python3.11/site-packages/IPython/core/ultratb.py\", line 1435, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/home/sidd462/miniconda3/lib/python3.11/site-packages/IPython/core/ultratb.py\", line 1326, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/home/sidd462/miniconda3/lib/python3.11/site-packages/IPython/core/ultratb.py\", line 1173, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/home/sidd462/miniconda3/lib/python3.11/site-packages/IPython/core/ultratb.py\", line 1063, in format_exception_as_a_whole\n","    self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []\n","    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/home/sidd462/miniconda3/lib/python3.11/site-packages/IPython/core/ultratb.py\", line 1115, in get_records\n","    style = stack_data.style_with_executing_node(style, self._tb_highlight)\n","            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/home/sidd462/miniconda3/lib/python3.11/site-packages/stack_data/core.py\", line 424, in style_with_executing_node\n","    class NewStyle(style):\n","  File \"/home/sidd462/miniconda3/lib/python3.11/site-packages/pygments/style.py\", line 91, in __new__\n","    ndef[4] = colorformat(styledef[3:])\n","              ^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/home/sidd462/miniconda3/lib/python3.11/site-packages/pygments/style.py\", line 58, in colorformat\n","    assert False, \"wrong color format %r\" % text\n","AssertionError: wrong color format 'ansiyellow'\n"]}],"source":["import random\n","random.seed(42)\n","tf.random.set_seed(42)\n","np.random.seed(42)"]},{"cell_type":"code","execution_count":3,"metadata":{"execution":{"iopub.execute_input":"2023-10-17T11:53:02.032846Z","iopub.status.busy":"2023-10-17T11:53:02.032004Z","iopub.status.idle":"2023-10-17T11:53:02.043180Z","shell.execute_reply":"2023-10-17T11:53:02.042421Z","shell.execute_reply.started":"2023-10-17T11:53:02.032815Z"},"trusted":true},"outputs":[],"source":["train = \"data/1-Kaggle-4/1-Train\"\n","test = \"data/1-Kaggle-4/2-Test\"\n","val = \"data/1-Kaggle-4/2-Test\""]},{"cell_type":"code","execution_count":4,"metadata":{"execution":{"iopub.execute_input":"2023-10-17T11:53:02.046323Z","iopub.status.busy":"2023-10-17T11:53:02.045591Z","iopub.status.idle":"2023-10-17T11:53:02.090995Z","shell.execute_reply":"2023-10-17T11:53:02.090098Z","shell.execute_reply.started":"2023-10-17T11:53:02.046294Z"},"trusted":true},"outputs":[{"name":"stdout","output_type":"stream","text":["Unexpected exception formatting exception. Falling back to standard exception\n"]},{"name":"stderr","output_type":"stream","text":["Traceback (most recent call last):\n","  File \"/home/sidd462/miniconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3526, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"/tmp/ipykernel_9869/2709436531.py\", line 2, in <module>\n","    img = cv2.imread(image_path, 0)\n","          ^^^\n","NameError: name 'cv2' is not defined\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/home/sidd462/miniconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 2120, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(\n","          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/home/sidd462/miniconda3/lib/python3.11/site-packages/IPython/core/ultratb.py\", line 1435, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/home/sidd462/miniconda3/lib/python3.11/site-packages/IPython/core/ultratb.py\", line 1326, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/home/sidd462/miniconda3/lib/python3.11/site-packages/IPython/core/ultratb.py\", line 1173, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/home/sidd462/miniconda3/lib/python3.11/site-packages/IPython/core/ultratb.py\", line 1063, in format_exception_as_a_whole\n","    self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []\n","    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/home/sidd462/miniconda3/lib/python3.11/site-packages/IPython/core/ultratb.py\", line 1115, in get_records\n","    style = stack_data.style_with_executing_node(style, self._tb_highlight)\n","            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/home/sidd462/miniconda3/lib/python3.11/site-packages/stack_data/core.py\", line 424, in style_with_executing_node\n","    class NewStyle(style):\n","  File \"/home/sidd462/miniconda3/lib/python3.11/site-packages/pygments/style.py\", line 91, in __new__\n","    ndef[4] = colorformat(styledef[3:])\n","              ^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/home/sidd462/miniconda3/lib/python3.11/site-packages/pygments/style.py\", line 58, in colorformat\n","    assert False, \"wrong color format %r\" % text\n","AssertionError: wrong color format 'ansiyellow'\n"]}],"source":["image_path = \"/kaggle/input/terrain-recognition/Data Main/train/Rocky/Rocky (1)_0_25.png\"\n","img = cv2.imread(image_path, 0)\n","img.shape"]},{"cell_type":"code","execution_count":5,"metadata":{"execution":{"iopub.execute_input":"2023-10-17T11:53:02.092778Z","iopub.status.busy":"2023-10-17T11:53:02.092189Z","iopub.status.idle":"2023-10-17T11:53:02.101825Z","shell.execute_reply":"2023-10-17T11:53:02.100877Z","shell.execute_reply.started":"2023-10-17T11:53:02.092739Z"},"trusted":true},"outputs":[{"name":"stdout","output_type":"stream","text":["4\n"]}],"source":["train_names = []\n","train_names = [f for f in sorted(os.listdir(train))]\n","\n","print(len(train_names)) "]},{"cell_type":"code","execution_count":6,"metadata":{"execution":{"iopub.execute_input":"2023-10-17T11:53:02.103869Z","iopub.status.busy":"2023-10-17T11:53:02.102983Z","iopub.status.idle":"2023-10-17T11:53:02.113904Z","shell.execute_reply":"2023-10-17T11:53:02.112858Z","shell.execute_reply.started":"2023-10-17T11:53:02.103840Z"},"trusted":true},"outputs":[{"name":"stdout","output_type":"stream","text":["4\n"]}],"source":["test_names = []\n","test_names = [f for f in sorted(os.listdir(test))]\n","\n","print(len(test_names)) "]},{"cell_type":"code","execution_count":7,"metadata":{"execution":{"iopub.execute_input":"2023-10-17T11:53:02.115981Z","iopub.status.busy":"2023-10-17T11:53:02.115293Z","iopub.status.idle":"2023-10-17T11:53:02.125759Z","shell.execute_reply":"2023-10-17T11:53:02.124789Z","shell.execute_reply.started":"2023-10-17T11:53:02.115953Z"},"trusted":true},"outputs":[{"name":"stdout","output_type":"stream","text":["4\n"]}],"source":["val_names = []\n","val_names = [f for f in sorted(os.listdir(val))]\n","\n","print(len(val_names)) "]},{"cell_type":"code","execution_count":8,"metadata":{"execution":{"iopub.execute_input":"2023-10-17T11:53:02.127762Z","iopub.status.busy":"2023-10-17T11:53:02.126868Z","iopub.status.idle":"2023-10-17T11:53:02.132605Z","shell.execute_reply":"2023-10-17T11:53:02.131763Z","shell.execute_reply.started":"2023-10-17T11:53:02.127709Z"},"trusted":true},"outputs":[{"name":"stdout","output_type":"stream","text":["Categories:\n","1-Grassy\n","2-Marshy\n","3-Rocky\n","4-Sandy\n"]}],"source":["print(\"Categories:\")\n","for i in train_names:\n","    print(i)"]},{"cell_type":"code","execution_count":9,"metadata":{"execution":{"iopub.execute_input":"2023-10-17T11:53:02.134578Z","iopub.status.busy":"2023-10-17T11:53:02.133787Z","iopub.status.idle":"2023-10-17T11:53:03.114977Z","shell.execute_reply":"2023-10-17T11:53:03.113942Z","shell.execute_reply.started":"2023-10-17T11:53:02.134549Z"},"trusted":true},"outputs":[{"name":"stdout","output_type":"stream","text":["1-Grassy: 8512\n","2-Marshy: 7727\n","3-Rocky: 7668\n","4-Sandy: 7664\n","Total images in training data: 31571\n"]}],"source":["category_dict1 = {}\n","images_per_category_dict1 = {}\n","category_images_path_dict1 = {}\n","\n","total_images = 0\n","\n","for i in range(len(train_names)):\n","    folder_path = train + '/' + str(train_names[i])\n","    category_dict1[i] = train_names[i]\n","    image_names = [img for img in sorted(os.listdir(folder_path))]\n","    images_per_category_dict1[i] = len(image_names)\n","    category_images_path_dict1[i] = image_names\n","    print('%s: %d' %(train_names[i], images_per_category_dict1[i]))\n","    total_images += images_per_category_dict1[i]\n","    \n","print('Total images in training data: %d' %(total_images))"]},{"cell_type":"code","execution_count":10,"metadata":{"execution":{"iopub.execute_input":"2023-10-17T11:53:03.118695Z","iopub.status.busy":"2023-10-17T11:53:03.118455Z","iopub.status.idle":"2023-10-17T11:53:04.016330Z","shell.execute_reply":"2023-10-17T11:53:04.015383Z","shell.execute_reply.started":"2023-10-17T11:53:03.118675Z"},"trusted":true},"outputs":[{"name":"stdout","output_type":"stream","text":["1-Grassy: 1824\n","2-Marshy: 1657\n","3-Rocky: 1644\n","4-Sandy: 1644\n","Total images in validation data: 6769\n"]}],"source":["category_dict2 = {}\n","images_per_category_dict2 = {}\n","category_images_path_dict2 = {}\n","\n","total_images = 0\n","\n","for i in range(len(test_names)):\n","    folder_path = test + '/' + str(test_names[i])\n","    category_dict2[i] = test_names[i]\n","\n","    image_names = [img for img in sorted(os.listdir(folder_path))]\n","    \n","    images_per_category_dict2[i] = len(image_names)\n","    category_images_path_dict2[i] = image_names\n","    \n","    print('%s: %d' %(test_names[i], images_per_category_dict2[i]))\n","    total_images += images_per_category_dict2[i]\n","    \n","print('Total images in validation data: %d' %(total_images))"]},{"cell_type":"code","execution_count":11,"metadata":{"execution":{"iopub.execute_input":"2023-10-17T11:53:04.017780Z","iopub.status.busy":"2023-10-17T11:53:04.017463Z","iopub.status.idle":"2023-10-17T11:53:04.032022Z","shell.execute_reply":"2023-10-17T11:53:04.031027Z","shell.execute_reply.started":"2023-10-17T11:53:04.017750Z"},"trusted":true},"outputs":[{"name":"stdout","output_type":"stream","text":["1-Grassy: 1824\n","2-Marshy: 1657\n","3-Rocky: 1644\n","4-Sandy: 1644\n","Total images in validation data: 6769\n"]}],"source":["category_dict3 = {}\n","images_per_category_dict3 = {}\n","category_images_path_dict3 = {}\n","\n","total_images = 0\n","\n","for i in range(len(val_names)):\n","    folder_path = test + '/' + str(val_names[i])\n","    category_dict3[i] = val_names[i]\n","\n","    image_names = [img for img in sorted(os.listdir(folder_path))]\n","    \n","    images_per_category_dict3[i] = len(image_names)\n","    category_images_path_dict3[i] = image_names\n","    \n","    print('%s: %d' %(val_names[i], images_per_category_dict3[i]))\n","    total_images += images_per_category_dict3[i]\n","    \n","print('Total images in validation data: %d' %(total_images))"]},{"cell_type":"code","execution_count":12,"metadata":{"execution":{"iopub.execute_input":"2023-10-17T11:53:04.034307Z","iopub.status.busy":"2023-10-17T11:53:04.033681Z","iopub.status.idle":"2023-10-17T11:53:27.401632Z","shell.execute_reply":"2023-10-17T11:53:27.400799Z","shell.execute_reply.started":"2023-10-17T11:53:04.034276Z"},"trusted":true},"outputs":[{"name":"stderr","output_type":"stream","text":["2023-10-17 17:44:01.114278: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.\n","To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.\n","2023-10-17 17:44:01.628011: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT\n"]},{"name":"stdout","output_type":"stream","text":["Found 31571 images belonging to 4 classes.\n","Found 6769 images belonging to 4 classes.\n"]}],"source":["from keras.preprocessing.image import ImageDataGenerator\n","\n","train_datagen = ImageDataGenerator(rescale=1./255,)\n","\n","test_datagen = ImageDataGenerator(rescale=1./255, validation_split= 0.2)\n","\n","train_generator = train_datagen.flow_from_directory(\n","        train,\n","        batch_size=8,\n","        target_size=(128, 128),\n","        class_mode='categorical')\n","\n","test_generator = test_datagen.flow_from_directory(\n","        val,\n","        batch_size=8,\n","        target_size=(128, 128),\n","        class_mode='categorical')"]},{"cell_type":"code","execution_count":13,"metadata":{"execution":{"iopub.execute_input":"2023-10-17T11:53:27.403132Z","iopub.status.busy":"2023-10-17T11:53:27.402814Z","iopub.status.idle":"2023-10-17T11:53:38.981126Z","shell.execute_reply":"2023-10-17T11:53:38.980238Z","shell.execute_reply.started":"2023-10-17T11:53:27.403103Z"},"trusted":true},"outputs":[],"source":["from keras.models import Sequential\n","from keras import layers\n","# model = Sequential()\n","# model.add(layers.Conv2D(128, (5, 5), activation = 'relu', input_shape = (128, 128, 3)))\n","# model.add(layers.Conv2D(128, (3,3), activation='relu'))\n","# model.add(layers.MaxPooling2D(pool_size = (2, 2)))\n","# model.add(layers.Dropout(0.25))\n","          \n","# model.add(layers.Conv2D(256, (3, 3), activation = 'relu'))\n","# model.add(layers.Conv2D(256, (3, 3), activation='relu'))\n","# model.add(layers.MaxPooling2D(pool_size = (2, 2)))\n","# model.add(layers.Dropout(0.25))\n","# model.add(layers.Flatten())                   \n","# model.add(layers.Dense(512, activation = 'relu'))\n","# model.add(layers.Dropout(0.5))\n","\n","# model.add(layers.Dense(4, activation = 'softmax'))\n","\n","# model = tf.keras.applications.efficientnet.EfficientNetB7(include_top=False, weights='imagenet')"]},{"cell_type":"code","execution_count":14,"metadata":{"execution":{"iopub.execute_input":"2023-10-17T11:53:38.982918Z","iopub.status.busy":"2023-10-17T11:53:38.982609Z","iopub.status.idle":"2023-10-17T11:53:40.768679Z","shell.execute_reply":"2023-10-17T11:53:40.767959Z","shell.execute_reply.started":"2023-10-17T11:53:38.982889Z"},"scrolled":true,"trusted":true},"outputs":[{"name":"stdout","output_type":"stream","text":["Unexpected exception formatting exception. Falling back to standard exception\n"]},{"name":"stderr","output_type":"stream","text":["Traceback (most recent call last):\n","  File \"/home/sidd462/miniconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3526, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"/tmp/ipykernel_9869/3470139634.py\", line 1, in <module>\n","    model.summary()\n","    ^^^^^\n","NameError: name 'model' is not defined\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/home/sidd462/miniconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 2120, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(\n","          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/home/sidd462/miniconda3/lib/python3.11/site-packages/IPython/core/ultratb.py\", line 1435, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/home/sidd462/miniconda3/lib/python3.11/site-packages/IPython/core/ultratb.py\", line 1326, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/home/sidd462/miniconda3/lib/python3.11/site-packages/IPython/core/ultratb.py\", line 1173, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/home/sidd462/miniconda3/lib/python3.11/site-packages/IPython/core/ultratb.py\", line 1063, in format_exception_as_a_whole\n","    self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []\n","    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/home/sidd462/miniconda3/lib/python3.11/site-packages/IPython/core/ultratb.py\", line 1115, in get_records\n","    style = stack_data.style_with_executing_node(style, self._tb_highlight)\n","            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/home/sidd462/miniconda3/lib/python3.11/site-packages/stack_data/core.py\", line 424, in style_with_executing_node\n","    class NewStyle(style):\n","  File \"/home/sidd462/miniconda3/lib/python3.11/site-packages/pygments/style.py\", line 91, in __new__\n","    ndef[4] = colorformat(styledef[3:])\n","              ^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/home/sidd462/miniconda3/lib/python3.11/site-packages/pygments/style.py\", line 58, in colorformat\n","    assert False, \"wrong color format %r\" % text\n","AssertionError: wrong color format 'ansiyellow'\n"]}],"source":["model.summary()"]},{"cell_type":"code","execution_count":15,"metadata":{"execution":{"iopub.execute_input":"2023-10-17T11:53:40.769944Z","iopub.status.busy":"2023-10-17T11:53:40.769621Z","iopub.status.idle":"2023-10-17T11:53:43.665849Z","shell.execute_reply":"2023-10-17T11:53:43.664912Z","shell.execute_reply.started":"2023-10-17T11:53:40.769915Z"},"trusted":true},"outputs":[{"name":"stdout","output_type":"stream","text":["Unexpected exception formatting exception. Falling back to standard exception\n"]},{"name":"stderr","output_type":"stream","text":["Traceback (most recent call last):\n","  File \"/home/sidd462/miniconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3526, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"/tmp/ipykernel_9869/3851805759.py\", line 1, in <module>\n","    model.trainable = False\n","    ^^^^^\n","NameError: name 'model' is not defined\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/home/sidd462/miniconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 2120, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(\n","          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/home/sidd462/miniconda3/lib/python3.11/site-packages/IPython/core/ultratb.py\", line 1435, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/home/sidd462/miniconda3/lib/python3.11/site-packages/IPython/core/ultratb.py\", line 1326, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/home/sidd462/miniconda3/lib/python3.11/site-packages/IPython/core/ultratb.py\", line 1173, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/home/sidd462/miniconda3/lib/python3.11/site-packages/IPython/core/ultratb.py\", line 1063, in format_exception_as_a_whole\n","    self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []\n","    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/home/sidd462/miniconda3/lib/python3.11/site-packages/IPython/core/ultratb.py\", line 1115, in get_records\n","    style = stack_data.style_with_executing_node(style, self._tb_highlight)\n","            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/home/sidd462/miniconda3/lib/python3.11/site-packages/stack_data/core.py\", line 424, in style_with_executing_node\n","    class NewStyle(style):\n","  File \"/home/sidd462/miniconda3/lib/python3.11/site-packages/pygments/style.py\", line 91, in __new__\n","    ndef[4] = colorformat(styledef[3:])\n","              ^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/home/sidd462/miniconda3/lib/python3.11/site-packages/pygments/style.py\", line 58, in colorformat\n","    assert False, \"wrong color format %r\" % text\n","AssertionError: wrong color format 'ansiyellow'\n"]}],"source":["model.trainable = False\n","model1 = Sequential([\n","    model,\n","    layers.GlobalMaxPooling2D(),\n","    layers.Dense(512, activation  =\"relu\"),\n","    layers.Dense(4, activation = \"softmax\")\n","])\n"]},{"cell_type":"code","execution_count":16,"metadata":{"execution":{"iopub.execute_input":"2023-10-17T11:53:43.667941Z","iopub.status.busy":"2023-10-17T11:53:43.667156Z","iopub.status.idle":"2023-10-17T11:53:43.717985Z","shell.execute_reply":"2023-10-17T11:53:43.717158Z","shell.execute_reply.started":"2023-10-17T11:53:43.667909Z"},"trusted":true},"outputs":[{"name":"stdout","output_type":"stream","text":["Unexpected exception formatting exception. Falling back to standard exception\n"]},{"name":"stderr","output_type":"stream","text":["Traceback (most recent call last):\n","  File \"/home/sidd462/miniconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3526, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"/tmp/ipykernel_9869/1054623878.py\", line 1, in <module>\n","    model1.summary()\n","    ^^^^^^\n","NameError: name 'model1' is not defined\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/home/sidd462/miniconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 2120, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(\n","          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/home/sidd462/miniconda3/lib/python3.11/site-packages/IPython/core/ultratb.py\", line 1435, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/home/sidd462/miniconda3/lib/python3.11/site-packages/IPython/core/ultratb.py\", line 1326, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/home/sidd462/miniconda3/lib/python3.11/site-packages/IPython/core/ultratb.py\", line 1173, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/home/sidd462/miniconda3/lib/python3.11/site-packages/IPython/core/ultratb.py\", line 1063, in format_exception_as_a_whole\n","    self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []\n","    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/home/sidd462/miniconda3/lib/python3.11/site-packages/IPython/core/ultratb.py\", line 1115, in get_records\n","    style = stack_data.style_with_executing_node(style, self._tb_highlight)\n","            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/home/sidd462/miniconda3/lib/python3.11/site-packages/stack_data/core.py\", line 424, in style_with_executing_node\n","    class NewStyle(style):\n","  File \"/home/sidd462/miniconda3/lib/python3.11/site-packages/pygments/style.py\", line 91, in __new__\n","    ndef[4] = colorformat(styledef[3:])\n","              ^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/home/sidd462/miniconda3/lib/python3.11/site-packages/pygments/style.py\", line 58, in colorformat\n","    assert False, \"wrong color format %r\" % text\n","AssertionError: wrong color format 'ansiyellow'\n"]}],"source":["model1.summary()"]},{"cell_type":"code","execution_count":17,"metadata":{"execution":{"iopub.execute_input":"2023-10-17T11:53:43.719730Z","iopub.status.busy":"2023-10-17T11:53:43.719219Z","iopub.status.idle":"2023-10-17T11:53:43.742072Z","shell.execute_reply":"2023-10-17T11:53:43.741120Z","shell.execute_reply.started":"2023-10-17T11:53:43.719699Z"},"trusted":true},"outputs":[{"name":"stdout","output_type":"stream","text":["Unexpected exception formatting exception. Falling back to standard exception\n"]},{"name":"stderr","output_type":"stream","text":["Traceback (most recent call last):\n","  File \"/home/sidd462/miniconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3526, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"/tmp/ipykernel_9869/3534434978.py\", line 2, in <module>\n","    model1.compile(loss='categorical_crossentropy', optimizer=optimizers.Adam(), metrics=['accuracy'])\n","    ^^^^^^\n","NameError: name 'model1' is not defined\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/home/sidd462/miniconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 2120, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(\n","          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/home/sidd462/miniconda3/lib/python3.11/site-packages/IPython/core/ultratb.py\", line 1435, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/home/sidd462/miniconda3/lib/python3.11/site-packages/IPython/core/ultratb.py\", line 1326, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/home/sidd462/miniconda3/lib/python3.11/site-packages/IPython/core/ultratb.py\", line 1173, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/home/sidd462/miniconda3/lib/python3.11/site-packages/IPython/core/ultratb.py\", line 1063, in format_exception_as_a_whole\n","    self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []\n","    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/home/sidd462/miniconda3/lib/python3.11/site-packages/IPython/core/ultratb.py\", line 1115, in get_records\n","    style = stack_data.style_with_executing_node(style, self._tb_highlight)\n","            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/home/sidd462/miniconda3/lib/python3.11/site-packages/stack_data/core.py\", line 424, in style_with_executing_node\n","    class NewStyle(style):\n","  File \"/home/sidd462/miniconda3/lib/python3.11/site-packages/pygments/style.py\", line 91, in __new__\n","    ndef[4] = colorformat(styledef[3:])\n","              ^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/home/sidd462/miniconda3/lib/python3.11/site-packages/pygments/style.py\", line 58, in colorformat\n","    assert False, \"wrong color format %r\" % text\n","AssertionError: wrong color format 'ansiyellow'\n"]}],"source":["from keras import optimizers\n","model1.compile(loss='categorical_crossentropy', optimizer=optimizers.Adam(), metrics=['accuracy'])"]},{"cell_type":"code","execution_count":18,"metadata":{"execution":{"iopub.execute_input":"2023-10-17T11:53:43.743803Z","iopub.status.busy":"2023-10-17T11:53:43.743466Z","iopub.status.idle":"2023-10-17T11:53:43.749393Z","shell.execute_reply":"2023-10-17T11:53:43.747223Z","shell.execute_reply.started":"2023-10-17T11:53:43.743774Z"},"trusted":true},"outputs":[{"name":"stdout","output_type":"stream","text":["Unexpected exception formatting exception. Falling back to standard exception\n"]},{"name":"stderr","output_type":"stream","text":["Traceback (most recent call last):\n","  File \"/home/sidd462/miniconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3526, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"/tmp/ipykernel_9869/3991112978.py\", line 1, in <module>\n","    EarlyStopping_1=tf.keras.callbacks.EarlyStopping(monitor='val_loss', patience = 4, verbose = 1)\n","                    ^^\n","NameError: name 'tf' is not defined\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/home/sidd462/miniconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 2120, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(\n","          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/home/sidd462/miniconda3/lib/python3.11/site-packages/IPython/core/ultratb.py\", line 1435, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/home/sidd462/miniconda3/lib/python3.11/site-packages/IPython/core/ultratb.py\", line 1326, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/home/sidd462/miniconda3/lib/python3.11/site-packages/IPython/core/ultratb.py\", line 1173, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/home/sidd462/miniconda3/lib/python3.11/site-packages/IPython/core/ultratb.py\", line 1063, in format_exception_as_a_whole\n","    self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []\n","    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/home/sidd462/miniconda3/lib/python3.11/site-packages/IPython/core/ultratb.py\", line 1115, in get_records\n","    style = stack_data.style_with_executing_node(style, self._tb_highlight)\n","            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/home/sidd462/miniconda3/lib/python3.11/site-packages/stack_data/core.py\", line 424, in style_with_executing_node\n","    class NewStyle(style):\n","  File \"/home/sidd462/miniconda3/lib/python3.11/site-packages/pygments/style.py\", line 91, in __new__\n","    ndef[4] = colorformat(styledef[3:])\n","              ^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/home/sidd462/miniconda3/lib/python3.11/site-packages/pygments/style.py\", line 58, in colorformat\n","    assert False, \"wrong color format %r\" % text\n","AssertionError: wrong color format 'ansiyellow'\n"]}],"source":["EarlyStopping_1=tf.keras.callbacks.EarlyStopping(monitor='val_loss', patience = 4, verbose = 1)"]},{"cell_type":"code","execution_count":19,"metadata":{"execution":{"iopub.execute_input":"2023-10-17T11:53:43.751439Z","iopub.status.busy":"2023-10-17T11:53:43.750636Z","iopub.status.idle":"2023-10-17T11:53:43.760374Z","shell.execute_reply":"2023-10-17T11:53:43.759441Z","shell.execute_reply.started":"2023-10-17T11:53:43.751410Z"},"trusted":true},"outputs":[],"source":["# history = model1.fit(train_generator, epochs = 50, validation_data = test_generator, verbose = 1, callbacks = EarlyStopping_1)"]},{"cell_type":"code","execution_count":20,"metadata":{"execution":{"iopub.execute_input":"2023-10-17T11:53:43.761988Z","iopub.status.busy":"2023-10-17T11:53:43.761704Z","iopub.status.idle":"2023-10-17T11:53:43.772143Z","shell.execute_reply":"2023-10-17T11:53:43.771312Z","shell.execute_reply.started":"2023-10-17T11:53:43.761961Z"},"trusted":true},"outputs":[],"source":["# val_acc = history.history[\"val_accuracy\"]\n","# acc = history.history[\"accuracy\"]\n","\n","# plt.plot(acc)\n","# plt.plot(val_acc)\n","# plt.legend(['Train', 'Validation'], loc='upper left')\n","# plt.title('model accuracy')\n","# plt.ylabel('accuracy')\n","# plt.xlabel('epoch')"]},{"cell_type":"code","execution_count":21,"metadata":{"execution":{"iopub.execute_input":"2023-10-17T11:53:43.773965Z","iopub.status.busy":"2023-10-17T11:53:43.773196Z","iopub.status.idle":"2023-10-17T11:53:43.782394Z","shell.execute_reply":"2023-10-17T11:53:43.781545Z","shell.execute_reply.started":"2023-10-17T11:53:43.773907Z"},"trusted":true},"outputs":[],"source":["# history.history\n"]},{"cell_type":"code","execution_count":22,"metadata":{"execution":{"iopub.execute_input":"2023-10-17T11:53:43.784231Z","iopub.status.busy":"2023-10-17T11:53:43.783462Z","iopub.status.idle":"2023-10-17T11:53:43.794118Z","shell.execute_reply":"2023-10-17T11:53:43.793139Z","shell.execute_reply.started":"2023-10-17T11:53:43.784179Z"},"trusted":true},"outputs":[],"source":["# import matplotlib.pyplot as plt\n","\n","\n","# val_acc = history.history[\"val_loss\"]\n","# acc = history.history[\"loss\"]\n","\n","# plt.plot(acc, color='blue')\n","# plt.plot(val_acc, color='red')\n","# plt.legend(['loss', 'val_loss'], loc='upper left')\n","# plt.title('Model Loss')\n","# plt.ylabel('Loss')\n","# plt.xlabel('Epoch')\n","# plt.show()\n"]},{"cell_type":"code","execution_count":23,"metadata":{"execution":{"iopub.execute_input":"2023-10-17T11:53:43.795782Z","iopub.status.busy":"2023-10-17T11:53:43.795444Z","iopub.status.idle":"2023-10-17T11:53:44.262467Z","shell.execute_reply":"2023-10-17T11:53:44.261249Z","shell.execute_reply.started":"2023-10-17T11:53:43.795742Z"},"trusted":true},"outputs":[{"name":"stderr","output_type":"stream","text":["/home/sidd462/miniconda3/lib/python3.11/site-packages/tensorflow_addons/utils/tfa_eol_msg.py:23: UserWarning: \n","\n","TensorFlow Addons (TFA) has ended development and introduction of new features.\n","TFA has entered a minimal maintenance and release mode until a planned end of life in May 2024.\n","Please modify downstream libraries to take dependencies from other repositories in our TensorFlow community (e.g. Keras, Keras-CV, and Keras-NLP). \n","\n","For more information see: https://github.com/tensorflow/addons/issues/2807 \n","\n","  warnings.warn(\n"]},{"name":"stderr","output_type":"stream","text":["2023-10-17 17:44:04.643101: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node\n","Your kernel may have been built without NUMA support.\n","2023-10-17 17:44:04.662215: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node\n","Your kernel may have been built without NUMA support.\n","2023-10-17 17:44:04.662273: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node\n","Your kernel may have been built without NUMA support.\n","2023-10-17 17:44:04.664151: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node\n","Your kernel may have been built without NUMA support.\n","2023-10-17 17:44:04.664274: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node\n","Your kernel may have been built without NUMA support.\n","2023-10-17 17:44:04.664310: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node\n","Your kernel may have been built without NUMA support.\n","2023-10-17 17:44:05.355767: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node\n","Your kernel may have been built without NUMA support.\n","2023-10-17 17:44:05.355831: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node\n","Your kernel may have been built without NUMA support.\n","2023-10-17 17:44:05.355837: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1726] Could not identify NUMA node of platform GPU id 0, defaulting to 0.  Your kernel may not have been built with NUMA support.\n","2023-10-17 17:44:05.355857: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node\n","Your kernel may have been built without NUMA support.\n","2023-10-17 17:44:05.355878: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1639] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 9386 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 4070, pci bus id: 0000:01:00.0, compute capability: 8.9\n","/home/sidd462/miniconda3/lib/python3.11/site-packages/vit_keras/utils.py:81: UserWarning: Resizing position embeddings from 12, 12 to 4, 4\n","  warnings.warn(\n"]},{"name":"stdout","output_type":"stream","text":["Epoch 1/50\n"]},{"ename":"","evalue":"","output_type":"error","traceback":["\u001b[1;31mThe Kernel crashed while executing code in the the current cell or a previous cell. Please review the code in the cell(s) to identify a possible cause of the failure. Click <a href='https://aka.ms/vscodeJupyterKernelCrash'>here</a> for more info. View Jupyter <a href='command:jupyter.viewOutput'>log</a> for further details."]}],"source":["from vit_keras import vit\n","import tensorflow as tf\n","\n","# Create the ViT model\n","def create_vit_model():\n","    vit_model = vit.vit_l32(\n","        image_size=128,\n","        activation='softmax',\n","        pretrained=True,\n","        include_top=True,\n","        pretrained_top=False,\n","        classes=4\n","    )\n","    \n","    model = tf.keras.Sequential([\n","        tf.keras.layers.InputLayer(input_shape=(128, 128, 3)),\n","        vit_model,\n","        tf.keras.layers.Dense(4, activation='softmax')\n","    ])\n","    \n","    return model\n","\n","# Model Configuration\n","input_shape = (128, 128, 3)  # Match with your input shape\n","num_classes = 4  # Number of output classes\n","\n","# Create and compile the model\n","model = create_vit_model()\n","model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])\n","\n","# Model Training\n","# Assuming train_generator and test_generator are already defined in your code\n","model.fit(train_generator, epochs=50, validation_data=test_generator)\n"]},{"cell_type":"code","execution_count":null,"metadata":{"trusted":true},"outputs":[{"name":"stderr","output_type":"stream","text":["2023-10-17 17:37:11.473725: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.\n","To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.\n","2023-10-17 17:37:12.928541: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT\n","2023-10-17 17:37:14.549868: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node\n","Your kernel may have been built without NUMA support.\n","2023-10-17 17:37:14.841895: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node\n","Your kernel may have been built without NUMA support.\n","2023-10-17 17:37:14.841945: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node\n","Your kernel may have been built without NUMA support.\n"]},{"data":{"text/plain":["[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),\n"," PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]"]},"execution_count":1,"metadata":{},"output_type":"execute_result"}],"source":["import tensorflow as tf\n","\n","tf.config.experimental.list_physical_devices()\n"]},{"cell_type":"code","execution_count":null,"metadata":{},"outputs":[],"source":[]}],"metadata":{"kernelspec":{"display_name":"Python 3","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.11.4"}},"nbformat":4,"nbformat_minor":4}
